# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Problem name
        description: 'Problem to setup'
        # Default value if no value is explicitly provided
        default: 'Sod'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-latest:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "install dependencies"
      run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev
          which mpif90
          # parallel hdf5 with fortran
          sudo apt-get install libhdf5-mpi-dev
    - name: "setup problem and execute"
      # make a site if required for github actions    
      run: |           
          pwd
          ls
          which h5pfc
          which mpif90
          cd /usr/local
          sudo mkdir mpich2
          cd mpich2
          sudo mkdir bin/
          sudo ln -s /usr/bin/* /usr/local/mpich2//bin/
          ls -ltrh /usr/local/mpich2//bin/mpif90
          ./setup ${{ github.event.inputs.name }} -auto -debug
          cd object
          mpiexec -np 2 ./flash5     
